name = "PlutoEducation"
uuid = "f6268fb4-b0b0-4b88-af26-5408c475f00e"
version = "0.0.1"
authors = ["Fons van der Plas <fonsvdplas@gmail.com>"]


[deps]

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
